# Generated by Django 5.1.3 on 2024-11-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_attendancerecord_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='emp_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
