# Generated by Django 5.1.3 on 2024-11-18 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_remove_attendancerecord_emp_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='face_encoding',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_scan_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
