# Generated by Django 5.1.3 on 2024-11-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_userprofile_face_encoding_userprofile_last_scan_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_faces/'),
        ),
    ]
